version: "3.9"

services:
    db:
      image: postgres
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    test:
      build:
        context: .
        cache_from:
          - fluffy-octo-system-test:latest
      image: fluffy-octo-system-test
      volumes:
        - .:/fluffy-octo-system
      command: bundle exec rspec
      env_file:
        - '.env.test'
      ports:
        - "3000:3000"
      depends_on:
        - db
volumes:
  postgres_test_master_data:
    driver: local